catppuccin.conf
Hi,
I was getting a syntax error in tmux if I uncommented "parent_dir/current_dir" window status format. Seems like it was caused by double quotes in echo command which closed the one that format string was enclosed in. 
Fixed it by replacing `"` with `'` in echo command.
If I missed something and this is not a bug then I am sorry and you can disregard this PR.
=> fix: syntax error when parent_dir enabled

README.md, catppuccin-frappe.conf, catppuccin-latte.conf, catppuccin-macchiato.conf, catppuccin-mocha.conf
* add all catppuccin themes to separate config files
* update readme to include word on choosing out your desired theme
- [#10](https://github.com/catppuccin/tmux/issues/10)
The following screenshots display different tmux modes/states (from top left, in clockwise rotation: prefix input, copy mode, clock, command mode):
**Latte**
**Frappe**
**Macchiato**
**Mocha**
=> feat(conf): add all catppuccin themes, split config

.gitignore, README.md, catppuccin-frappe.tmuxtheme, catppuccin-latte.tmuxtheme, catppuccin-macchiato.tmuxtheme, catppuccin-mocha.tmuxtheme, catppuccin.tmux
This option, for now, defaults to `false`. This is just so it keeps the
initial design intention for the original design of the plugin. I may
flip it or change the name of the variable in future commits. This patch
is addressing catppuccin/tmux#16.
Alright, this closes #16 when it's merged into the default branch. If anyone would like to test this out locally, you _should_ be able to set a new remote to my GH fork and then change branches to `add-option-to-display-folders`.
The commands to do that in your local Git repository should be:
```sh
cd ~/.tmux/plugins/tmux
git remote add rogeruiz https://github.com/rogeruiz/tmux.git
git fetch --all
git checkout add-option-to-display-folders
```
Afterwards, you can follow the documentation in the `README.md` to turn on the feature. Remember to …
=> feat(window_tabs_enabled): Adding support for window tabs rather than directory tabs

.gitignore, catppuccin.tmux
1. Don't create temporary files. It fixes an error for me when loading theme from a read-only filesystem (Nix store in my case).
2. Calling `tmux` for every variable is pretty slow. I changed it to aggregate all commands in a variable, then call it once.
Before:
```
Executed in   98.28 millis    fish           external
usr time   53.09 millis    0.00 micros   53.09 millis
sys time   20.00 millis  667.00 micros   19.33 millis
```
After:
```
Executed in   22.50 millis    fish           external
usr time   14.36 millis  618.00 micros   13.74 millis
sys time    5.53 millis  115.00 micros    5.41 millis
```
My first version printed commands in a function. Then I did `load_theme | tmux source-file -`, but looks like reading commands from stdin is pretty recent change in tmux (3.1): …
=> Improve performance

README.md, catppuccin.tmux
Related to #45 - I noticed that the datetime icon was no longer working with a version 3.0 Nerd Font. I think #45 tackles the short term need for the project, and this PR brings a long term solution where users can customize any of the icons used by the project. 
This is my first contribution to anything tmux related - so if I'm missing big formatting things feel free to let me know 😄
=> Customizable icons 

README.md, status/battery.sh
Battery module
Requirements
This module depends on [tmux-battery](https://github.com/tmux-plugins/tmux-battery/tree/master).
Install
The prefered way to install tmux-battery is using [TPM](https://github.com/tmux-plugins/tpm).
Configure
Load tmux-battery after you load catppuccin.
set -g @plugin 'catppuccin/tmux'
...
set -g @plugin 'tmux-plugins/tmux-battery'
Add the battery module to the status modules list.
set -g @catppuccin_status_modules" "... battery ..."
=> feat(battery): add battery module

catppuccin.tmux
A drawback for the custom status icons is that the window_marked_flag was only added in [tmux 3.1](https://github.com/tmux/tmux/blob/3.1/CHANGES#L120C26-L120C26).
For context Debian 11/Bullseye is the first debian release with tmux 3.1 (or newer):
- [Debian 10/Buster - tmux](https://packages.debian.org/buster/tmux)
- [Debian 11/Bullseye - tmux](https://packages.debian.org/bullseye/tmux)
=> Remove sed dependencies

catppuccin.tmux
These constants were added in commit 4d4bf19 and became unused in commit 56a447094a5c3f0eff9fc7b20d40ad81e5660bfe
=> fix(main): remove old constants

README.md, catppuccin.tmux
Added possibility of adding modules also to the left of the status line. 
Example:
```sh
set -g @catppuccin_status_modules "host"
set -g @catppuccin_left_status_modules "session"
```
=> feat(status): allow modules in left_status

README.md, status/cpu.sh
CPU module
Requirements
This module depends on [`tmux-cpu`](https://github.com/tmux-plugins/tmux-cpu).
Install
The prefered way to install tmux-cpu is using [TPM](https://github.com/tmux-plugins/tpm).
Configure
Load tmux-cpu after you load catppuccin.
set -g @plugin 'catppuccin/tmux'
...
set -g @plugin 'tmux-plugins/tmux-cpu'
Add the cpu module to the status modules list.
set -g @catppuccin_status_modules" "... cpu ..."
=> feat(cpu): add cpu module

README.md, window/window_current_format.sh, window/window_default_format.sh
Adding a variable to allow the modification of the current window while otherwise defaulting to the original orange. Likewise was done for the default window, but with the gray. The variable names used were kept honest to the existing variables.
Addresses:
#80
Relevant options added:
`set -g @catppuccin_window_current_color "#DDB6F2"`
`set -g @catppuccin_window_default_background "#333333"`
=> Feature: Window BG Color

README.md, status/weather.sh
Weather module
Requirements
This module depends on https://github.com/xamut/tmux-weather.
Install
The preferred way to install tmux-weather is using TPM.
Configure
Load tmux-weather after you load catppuccin.
set -g @plugin 'catppuccin/tmux'
...
set -g @plugin 'xamut/tmux-weather'
Add the weather module to the status modules list.
set -g @catppuccin_status_modules" "... weather ..."
=> feat(weather): add weather module for xamut/tmux-weather

catppuccin.tmux
- Check if file exists instead of sourcing and checking for an error
- Loop over module directories
- Fix `module_index`: was treated as a string ("0", "0+1", "0+1+1")
=> refactor(load_modules)

README.md
I noticed that the wrong option was being referred to on the documentation when setting the default window color.
=> docs(README.md) use correct option for default window color

catppuccin.tmux
In  default tmux, when multiple panes are displayed (i.e., not zoomed) and pane_synchronized is true (i.e., by using `:set synchronize-panes on`), the active pane's border color will change from green to red ([source link][tmux-link]). We should to retain this behavior.
[tmux-link]:https://github.com/tmux/tmux/blob/0b355ae8114511e1ff6359272b164f1cdf718e80/options-table.c#L969
=> feat(pane): different border color if pane_synchronized

README.md, catppuccin.tmux
This adds a new config entry for setting the default status bar visibility on load, rather than forcing it to be on by default.
=> feat(config): allow status bar to be disabled by default

README.md, catppuccin.tmux
Sometimes the window status icons get crowded,
After the change,
=> Add space to default window status icons

README.md, custom/README.md, custom/example.sh
As requested by @sgoudham in #90
=> Clarify creating a custom module

README.md, status/clima.sh
=> Add tmux-clima as another module for weather

catppuccin.tmux
This PR makes it the responsibility of the theme to ensure that the correct space is set between the window text, window status icon and window status right separator.
Old:
New:
=> fix(window_status): fix window space

README.md, status/uptime.sh
The uptime plugin has some issue with minute formatting.
The sed command is based on https://stackoverflow.com/a/28353785.
```bash
$ bash uptimes
03:14:20 up 1 min,  2 users,  load average: 2.28, 1.29, 0.50
new: 1m
old: 1 min
04:12:29 up 59 min,  5 users,  load average: 0.06, 0.08, 0.48
new: 59m
old: 59 min
05:14:09 up  2:01,  5 users,  load average: 0.13, 0.10, 0.45
new: 2h 01m
old: 2h 01m
03:13:19 up 1 day, 0 min,  8 users,  load average: 0.01, 0.04, 0.05
new: 1d 0m
old: 1d 0 min
04:13:19 up 1 day,  1:00,  8 users,  load average: 0.02, 0.05, 0.21
new: 1d 1h 00m
old: 1d 1h 00m
12:49:10 up 25 days, 21:30, 28 users,  load average: 0.50, 0.66, 0.52
new: 25d 21h 30m
old: 25d 21h 30m
```
```bash
$ cat uptimes.sh 
#!/usr/bin/env bash
while read line; do
echo "$line"
echo -en "\t new: "
echo …
```
=> feat(uptime): replace plugin with sed

.github/scripts/test.bash, .github/workflows/shellcheck.yml, .shellcheckrc, builder/module_builder.sh, builder/window_builder.sh, catppuccin.tmux, pane/pane_default_format.sh, status/application.sh, status/battery.sh, status/clima.sh, status/cpu.sh, status/date_time.sh, status/directory.sh, status/host.sh, status/load.sh, status/session.sh, status/uptime.sh, status/user.sh, status/weather.sh, utils/module_utils.sh, window/window_current_format.sh, window/window_default_format.sh
Todo:
local command used: `shellcheck -a catppuccin.tmux $(ls custom/*.sh pane/*.sh status/*.sh window/*.sh)`
=> Cleanup shellcheck warnings

.github/workflows/shellcheck.yml
Don't remove checking for `catppuccin.tmux`
=> fixup! Cleanup shellcheck warnings (#178)

catppuccin.tmux
When using `default` for `@catppuccin_status_background`, it still keeps background color for `message-style`. You can see it when you type a command in `tmux`.
Current implementation (with `@catppuccin_status_background` `"default"`):
Respecting `@catppuccin_status_background` (with `@catppuccin_status_background` `"default"`):
=> Respect `status_background` in `message-style`

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/meta.yml
This PR adds some issue templates to improve the quality of issues raised, as well as introduce GitHub discussions for general questions and for people to show off their Catppuccin tmux configs.
Pressing the `New issue` button now presents the following UI:
Expand the dropdowns below to see how each issue template renders.
<details>
<summary>Bug Report</summary>
</details>
<details>
<summary>Enhancement Issue</summary>
</details>
<details>
<summary>Meta Issue</summary>
</details>
`Ask A Question` and `Show & Tell` link off to GitHub discussions. I think it'll be good to add discussion templates for these categories but I'd regard that as out of scope here and should be implemented by another PR.
I've left the `Community Discord` link in because …
=> docs: add issue templates

.github/ISSUE_TEMPLATE/config.yml
I renamed the discussion category and forgot to update the link. This PR updates the link to be correct
=> chore(issue-templates): fix `show & tell` discussion link

status/battery.sh
fix #188 .
Add new icon to overwrite tmux-battery attached status in order to be consistent with other icon styles.
According to [https://github.com/tmux-plugins/tmux-battery/pull/4](url),`attached` status used to alert user powerline c onnect fine but battery might be not charged.
tmux-battery attached icon is '⚠️ ',and new icon is like:
Alert battery icon is used to express discharging,so i use this icon.
=> fix(status): support tmux-battery attached status icon

builder/window_builder.sh
Middle separator color was inverted when number position left.
Before:
After:
=> fix(window_builder): number position left

README.md, catppuccin.tmux, utils/interpolate_utils.sh, utils/tmux_utils.sh
Allow reuse of colors defined in `catppuccin-<flavor>.tmuxtheme` files for user provided options, using the format `#{thm_<color>}`.
=> Feat: interpolate colors

catppuccin.tmux
macos bash version (3.2.57) does not support the `"${val:1:-1}"` syntax
=> fixup! Feat: interpolate colors (#208)

tmux.tera
whiskers 2.1.1 no longer eats trailing newlines
=> build: bump whiskers to 2.1.1

utils/module_utils.sh, utils/tmux_utils.sh
print/echo a warning when a `catppuccin_status_modules_right/left` is trying to load a none existing module.
This does only work when reloading (`tmux source ~/.tmux.conf` / `tmux source ~/.config/tmux/tmux.conf`)
closes #243
=> feat: warning when trying to load a missing module

builder/module_builder.sh
don't change `show_text`
closes: #252
=> fixup! fix: status module trailing space transparancy (#250)

README.md
Aims to close #248 
Bug notated in that issue is just an insignificant naming issue, this adds a note to the docs to explain it.
=> Update docs to explain color/background swap

status/uptime.sh
Previously, on machines where the logged-in user count is 1, the `sed` expression to filter out "... X users, ..." doesn't filter out "... X user, ...", leading to something like
```
1h 05,  1 user,  load average: 0.05, 0.72, 1.62m
```
being displayed in the module. When the user count is greater than 1 (e.g., after `ssh localhost`), the `uptime` module displays
```
1h 05m
```
as expected.
With this patch, the module display correctly when the user count is 1.
The Stack Overflow answer the `sed` expression is based on [^1][^2] doesn't seem to consider the case when the user count is 1.
[^1]: https://stackoverflow.com/a/28353785
[^2]: https://github.com/catppuccin/tmux/pull/163
=> fix(uptime): filter out singular "user" string in sed expression

.github/release-please-config.json
When a release is a draft release-please can't find it, see https://github.com/googleapis/release-please/issues/1650 for more info.
=> fix(ci): disable release-please draft releases

builder/window_builder.sh, catppuccin.tmux, pane/pane_default_format.sh, status/application.sh, status/battery.sh, status/clima.sh, status/cpu.sh, status/date_time.sh, status/directory.sh, status/gitmux.sh, status/host.sh, status/kube.sh, status/load.sh, status/pomodoro_plus.sh, status/session.sh, status/uptime.sh, status/user.sh, status/weather.sh, utils/tmux_utils.sh, window/window_current_format.sh, window/window_default_format.sh
Batching tmux show-options gives a significant start uptime decrease of up to 3 under linux (tested with bath bash-5.2.26 and 3.2.57).
~~On the bash version used by macos this however seems to have a negative impact. This was test in docker with as image `bash:3.2.57-alpine3.19`. The negative impact maybe from docker/alpine since in `bash:5.1-alpine3.19` it also had a negative impact but less.
Can anyone on macos see what the real effect is?~~
~~I think the the complexity increase is worth it if the "macos"/old bash/alpine hit is because of alpine, but would love to get more feedback on this.~~
Effect was docker/alpine build bash-3.2.57 and it works great.
Tested on 10 user configs (from issues) with and without batching and batching was always an improvement.
With defaults in the array …
=> perf: batch tmux show-options

README.md, utils/module_utils.sh
`set -g @catppuccin_status_modules_right " "` will try to load ` ` as a module same with `set -g @catppuccin_status_modules_left "session "`.
The proper way to clear modules is `set -g @catppuccin_status_modules_right "null"` 
Fixes: #263
=> feat: warn users of whitespace in module lists

utils/module_utils.sh, utils/tmux_utils.sh
`tmux_echo` now uses hooks this allows it to print on the first load. To cleanup the hooks every hook gets a _unique_ number/index, this is _not_ enforced.
=> feat: error/warning messages on first load

builder/module_builder.sh
When rendering status modules, there is a separator between the icon and the module text. Before, it was redundantly shown even when the module icon was disabled by the user.
=> Don't add icon separator if there is no icon for a status module

builder/window_builder.sh
Only works for catppuccin_window_status_icon_enable = yes
=> fix(window): don't prepend separator before empty status icon

catppuccin.tmux
fix: add missing batch options `catppuccin_pane{,_active}_border_style`
Fixes: #289
=> fix: add missing batch options `catppuccin_pane{,_active}_border_style`

README.md, catppuccin.tmux, utils/module_utils.sh
Most catppuccin ports have adopted the flavor spelling.
`@catppuccin_flavour` is still available but no longer documented and `@catppuccin_flavor` takes priority.
=> refactor: `@catppuccin_flavour` -> `@catppuccin_flavor`

builder/window_builder.sh, catppuccin.tmux
Don't print warning if  `@catppuccin_window_status` is not used
FIXES: #293
=> fix: warning `@catppuccin_window_status`

catppuccin.tmux
No longer warn when `@catppuccin_flavor` _and_ `@catppuccin_flavour` are not set
Fixes: #295
=> fix: warning `@catppuccin_flavour`

status/kube.sh
Need this to be interpreted when tmux status is updated rather than when this script executes as the value is set in the tmux env rather than the current shell
resolves #301
=> fix(kube): escape env var

README.md, builder/window_builder.sh, window/window_current_format.sh, window/window_default_format.sh
This pull request:
Allowed new configuration options:
```conf
set -g @catppuccin_window_current_left_separator "█"
set -g @catppuccin_window_current_middle_separator " 󰿟 "
set -g @catppuccin_window_current_right_separator "█"
```
Fixes #197
=> feat(status): window specific separator config

README.md
This took me way too long to realize there even is a way to "disable" (set to empty) a customization without changing the code. This PR addresses the issue and adds a note at the top of the customization section that every text-based customization may be null.
=> docs: add clarifying note in the README about null values

catppuccin_tmux.conf
Color names were replaced with upstream names.
=> fix: `thm_gray`` -> `thm_surface_0``

catppuccin_tmux.conf
This does not add extra option when using `tmux show -g` (or unsetting it later) and does not require expansion with `#{@`.
=> chore: replace `@message_background` with an hidden variable

tests/application_module.sh, tests/application_module_expected.txt, tests/default_options.sh, tests/default_options_expected.txt, tests/harness.sh, tests/helpers.sh
- fail tests if test scripts exit's with none 0 code
- don't expand option by default
- check all if colors are expanded
- check if module text is not expanded
=> chore: improve testing

catppuccin_options_tmux.conf, catppuccin_tmux.conf, status/application.conf, status/battery.conf, status/clima.conf, status/cpu.conf, status/date_time.conf, status/directory.conf, status/gitmux.conf, status/host.conf, status/kube.conf, status/load.conf, status/pomodoro_plus.conf, status/session.conf, status/uptime.conf, status/user.conf, status/weather.conf, utils/status_module.conf
- Adds support for window flags and flag icons
- Moves the spaced from before/after the icons to inside the icon default to save on boiler plate compares in tmux script.
- renames `catppuccin_icon_<icon_name>` to `catppuccin_window_flags_<icon_name>`, is this name to long?
=> feat(status/window): icons

README.md, catppuccin_options_tmux.conf
fix(readme): update the readme to include upgrade instructions
chore: release 1.0.0
=> fix(window): ensure the window formats are set correctly

README.md, status/README.md
=> fix(readme): remove -F when setting the status line

README.md, run_tests.sh, status/battery.conf, tests/battery_module.sh, tests/battery_module_expected.txt
Need the `battery_icon` format to expand as a literal for the battery plugin to find it and replace it.
=> Issue #342: Checking if battery_icon literal helps

README.md, status/README.md
Adds some additional clarity for what is required when setting the status modules.
> Based on the discussion in Issue #345.
=> docs: Issue #345 - clarifying steps for status modules

catppuccin_options_tmux.conf, catppuccin_tmux.conf, utils/status_module.conf
When changing the background of the status bar, I think the default background color of all modules should be this color. 
Therefore, the hard coded references to `default` and `thm_surface_1` in `utils/status_module.conf` should be in my opinion changed to `${CTP_MESSAGE_BACKGROUND}`. With this changes the background color of the status bar is always the same. 
I'm not so familiar with the new tmux configuration style. I hope that this is the correct way to solve the problem.
=> style(status): use @catppuccin_status_background as background color

.github/workflows/test.yml
`ubuntu-latest` is `ubuntu-24.04`, see https://github.com/actions/runner-images?tab=readme-ov-file#available-images.
`ubuntu24.04` has [tmux version `3.4-1build1`](https://packages.ubuntu.com/noble/tmux).
Don't know what the best option is 
- "upgrading" the tmux version
- another image, for example `ubuntu-22.04`
- matrix of `ubuntu-20.04`, `ubuntu-22.04`, `ubuntu-24.04`/`ubuntu-latest`
- building tmux from source, don't think this is a good idea just adding it to complete the list
=> fix(ci): update tmux in test workflow

catppuccin_tmux.conf
`middle_separator` is _not_ the same for fill `number` and `all`, for fill the colors are the same as text or color (or the reverse of middle sep with number fill).
before:
after:
Also changed where `@_ctp_w_left` is set since it was _always_ overwritten when the fill is number.
<details>
<summary>config</summary>
```tmux
set -g @catppuccin_window_status_style "custom"
set -g window-status-separator ""
set -g @catppuccin_window_default_text "#{pane_title}"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_middle_separator "█ "
set -g @catppuccin_window_right_separator ""
set -g @catppuccin_window_current_text "#{pane_title}"
set …
```
=> fix(window): middle separator colors

README.md
Looks like the Pocco81 link at the bottom links to the wrong github profile.
=> docs(README): fix incorrect link for Pocco

catppuccin_options_tmux.conf, status/README.md, tests/application_module_expected.txt, tests/battery_module_expected.txt, tests/cpu_module_expected.txt, utils/status_module.conf
**Before the change:**
With `@catppuccin_status_connect_separator` set to `yes` or `no`
**After the change:**
With `@catppuccin_status_connect_separator` set to `yes`
With `@catppuccin_status_connect_separator` set to `no`
=> fix: replace @_ctp_status_bg with @thm_surface_0 in module configurtion to properly show module separation

status/session.conf
The bg color of icon is always green.
I think the expands should be done later. There might be more cases.
This bug is observed on v2 but not v1.0.3.
=> Fix session status icon bg color change by client_prefix

.github/release-please-config.json
This PR adjusts the changelog sections so that `perf`, `revert` and `docs` commits are tracked in the CHANGELOG and are suitable candidates for the creation of a release please PR.
In an ideal world, the commits included in the CHANGELOG and the scopes responsible for the creation of the release please PR would be decoupled but it seems as though that is not currently possible.
=> build: allow release-please to release on more scopes

status/battery.conf, status/cpu.conf, status/gitmux.conf, status/kube.conf, status/load.conf, status/session.conf, status/uptime.conf, status/user.conf, status/weather.conf, tests/cpu_module_expected.txt, utils/status_module.conf
This PR fixes the issue #407 and enables dynamic color for text and icon in status modules.
E.g. the following custom module:
``` sh
%hidden MODULE_NAME='memory'
set-option -ogq '@ram_low_bg_color' '#{E:@thm_green}'
set-option -ogq '@ram_medium_bg_color' '#{E:@thm_yellow}'
set-option -ogq '@ram_high_bg_color' '#{E:@thm_red}'
set-option -ogq "@catppuccin_${MODULE_NAME}_icon" '<U+E266> '
set-option -ogq "@catppuccin_${MODULE_NAME}_color" '#{l:#{ram_bg_color}}'
set-option -ogq "@catppuccin_${MODULE_NAME}_text" ' #{l:#{ram_percentage}}'
source-file -F '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/utils/status_module.conf'
```
Results in the following status bar:
With the PR the expansions for the color parts in `utils/status_module.conf` are removed and the color can by changed dynamically:
Therefore, …
=> fix: Issue #407 and dynamic colors in status modules

catppuccin_options_tmux.conf, catppuccin_tmux.conf, docs/reference/configuration.md
This add the options `@catppuccin_window_number` and `@catppuccin_window_current_number` to format the window number so we can have something like:
```sh
set -g @catppuccin_window_number #[bold]Tab ###I
set -g @catppuccin_window_current_number #[bold]Tab ###I
```
=> feat: add option to format window number

catppuccin_tmux.conf
To enable the use of `@catppuccin_window_status_style "custom"`, we need to use the existing parameter @catppuccin_window_current_right_separator. This is necessary to ensure the correct separator is used in `window-status-current-format`.
Additionally, a `popup-style` change is required to maintain consistency with transparent background setups.
=> Use current window separators for the current window format

status/uptime.conf
`10:31  up 36 mins, 2 users, load averages: 2.55 4.87 6.81`
`9:42  up 10 days, 25 mins, 2 users, load averages: 4.71 4.27 4.00`
`18:43  up 21 days, 9 hrs, 2 users, load averages: 3.99 6.48 10.99`
```
Uptime String: 18:43  up 9 hrs, 2 users, load averages: 3.99 6.48 10.99
Current SED: 9 hrsm
Fixed SED: 9h
Uptime String: 18:44  up  9:01, 2 users, load averages: 4.94 6.21 10.55
Current SED: 9h 01m
Fixed SED: 9h 01m
Uptime String: 9:31  up 45 secs, 2 users, load averages: 105.51 24.01 8.61
Current SED: 45 secsm
Fixed SED: 45s
Uptime String: 9:32  up 2 mins, 2 users, load averages: 109.13 55.55 22.93
Current SED: 2sm
Fixed SED: 2m
Uptime String: 22:37:29 up 4 days,  9:44,  1 user,  load average: 0.07, 0.03, 0.01
Current SED: 4d 9h 44m
Fixed SED: 4d 9h 44m
Uptime String: 11:24  up  1:54, 2 …
```
=> fix: improve uptime status sed script to report correct units for a few uptime scenarios

catppuccin_tmux.conf
Use `catppuccin_window_current_left_separator` instead of `catppuccin_window_left_separator` when constructing the `window-status-current-style` option.
Previously, #443 fixed the unused `catppuccin_window_current_right_separator`, but `catppuccin_window_current_left_separator` remained unused. This PR addresses the left variable.
=> Fix: use the correct option for the left separator for the current window

catppuccin_options_tmux.conf, catppuccin_tmux.conf, docs/reference/configuration.md
This effectively lets users decide if they want an additional space, instead of it being hard-coded
=> fix(flags): remove additional space from flags

README.md
Problem in the show ```bash```
=> docs(README): fix codeblock indentation

README.md
Correct the plugin path for TPM in the readme. Fixes #476 
[TPM](https://github.com/tmux-plugins/tpm) recommends the directory `~/.tmux/plugins/tpm` be used as the installation directory in the README, which is likely what most users will choose. TPM can be installed into _any_ directory, but the readme should ideally mention the most common choice that users will have, which we can assume is going to be `~/.tmux/plugins`.
---
Tested this change on my  [current setup](https://github.com/ThomasCode92/dotfiles/blob/main/dot_tmux.conf), see screenshot below.
=> docs: Correct the plugin path for TPM in the readme

docs/reference/status-line.md, run_tests.sh, status/load.conf, tests/load_module.sh, tests/load_module_expected.txt
Fixed load status as per [PR 503](https://github.com/catppuccin/tmux/pull/503).
Used `uptime|awk '{split(substr($0, index($0, "load")), a, ":"); print a[2]}'` to set the text variable as suggested [here](https://github.com/tmux/tmux/wiki/FAQ#what-is-the-best-way-to-display-the-load-average-why-no-l).
=> fix: load status panel according to tmux suggestions

docs/tutorials/03-resetting-theme.md
1. 💬 Create the first draft for resetting theme 🏷️ b4c3472
> [!IMPORTANT]
> More updates coming soon as progress is made. Watch this space for updates
> soon.
This work is based on the work in catppuccin/tmux#500. Until that PR is merged,
this patch will remain a draft.
=> [docs] Reset themes documentation

catppuccin_options_tmux.conf, catppuccin_tmux.conf, docs/reference/configuration.md, docs/tutorials/02-custom-status.md
Recurring issues are being raised that options are not being applied,
where users have used '-o' to set options. '-o' instructs tmux
to only set the option if it is not already set. This is useful
in the plugin itself, but almost never useful for the end user.
=> docs: stop recommending `-o`

themes/catppuccin_frappe_tmux.conf, themes/catppuccin_latte_tmux.conf, themes/catppuccin_macchiato_tmux.conf, themes/catppuccin_mocha_tmux.conf
I'm not very familiar with tmux configuration or themes, let alone familiar with Catppuccin, so I'm not at all confident in this change, but this sure looked like unintentionally duplicated code, to I thought I'd fire off a PR. Feel free to reject for whatever reason.
=> fix(theme): Cleanup duplicate palette theme color
