README.md
Added link to my gh page.
Thanks for the chance to contribute @nekowinston !
=> docs(readme): add link to contributors list 😃 

README.md
Changed *.conf to *.tmuxtheme.
=> docs: README filepath changes

README.md, catppuccin.tmux
Added a new configurable date time component inspired by this PR: https://github.com/catppuccin/tmux/pull/35
=> feat(datetime): add new date time component

README.md
The third config code is missing `set -g @catppuccin_window_number_position "right"` setting.
It results in the following behavior.
N/A
N/A
Please check the type of change your PR introduces:
=> fix: Fix missing window number position in Config 3 in README

catppuccin.tmux
`@catppuccin_window_left_separator_inverse`
`@catppuccin_window_right_separator_inverse`
`@catppuccin_status_left_separator_inverse`
Bonus: `shfmt`.
=> Add config options

custom/README.md
The module template currently only shows how to display a static text. This PR clarifies how to use a command or script to display a dynamic text.
=> docs: demonstrate how to use a command or script

README.md
I'm not a tmux user but I believe these instructions are better, provided by @j-o-sh
Closes #123
=> docs(README.md): improve manual install steps

README.md, status/uptime.sh
The module is based on tmux plugin https://github.com/robhurring/tmux-uptime.
=> feat(uptime): add uptime module based on robhurring/tmux-uptime

README.md
Section load module was kind of borked, this fixes that
=> Fixed typos and formatting oversight in readme.md

.github/scripts/test.bash, .github/workflows/shellcheck.yml, .github/workflows/test.yml
Add a test workflow to see if everything works still works.
This will just test if nothing errors **not** if the all the options are correctly set.
=> ci: add testing & shellcheck workflows

README.md
=> docs(README.md): fix typo `prefered` -> `preferred`

builder/pane_builder.sh
=> fix(pane_builder): use default background instead of `thm_bg`

catppuccin.tmux
=> fixup! Feat: interpolate colors (#208)

status/application.sh
=> fix: better default for application.sh

README.md, status/kube.sh
Add suport to [kube-tmux](https://github.com/jonmosco/kube-tmux) in status bar
=> Add support to kube-tmux in status bar

builder/module_builder.sh
Thank you @64rl0 for noticing it and suggesting a fix.
Closes #242
=> fix: status module trailing space transparancy

builder/window_builder.sh, catppuccin.tmux, pane/pane_default_format.sh, status/application.sh, status/battery.sh, status/clima.sh, status/cpu.sh, status/date_time.sh, status/directory.sh, status/gitmux.sh, status/host.sh, status/kube.sh, status/load.sh, status/pomodoro_plus.sh, status/session.sh, status/uptime.sh, status/user.sh, status/weather.sh, utils/tmux_utils.sh, window/window_current_format.sh, window/window_default_format.sh
=> perf: batch tmux show

utils/tmux_utils.sh
=> fix: escaping in options

catppuccin_options_tmux.conf, catppuccin_tmux.conf, tests/default_options.sh, tests/default_options_expected.txt, tests/pane_styling_expected.txt
Options where being expanded to much
=> fix: pane-format

catppuccin_tmux.conf, tests/pane_styling_expected.txt
Minor fix to replace the incorrect setup for the right side pane separator
=> Added missing pane right separator setting

catppuccin_tmux.conf, run_tests.sh, status/README.md, status/battery.conf, status/clima.conf, status/cpu.conf, status/pomodoro_plus.conf, status/weather.conf, tests/application_module.sh, tests/application_module_expected.txt, tests/cpu_module.sh, tests/cpu_module_expected.txt, utils/status_module.conf
=> Status line fixes

catppuccin_tmux.conf
=> Revert "fix(window): middle separator colors"

.github/release-please-config.json, CONTRIBUTING.md
This will make the changelog a little easier to parse, and make it clearer what is changed & added in each release.
Inspired by https://keepachangelog.com/en/1.1.0/
=> Configure release please to pickup extra commit types

docs/reference/configuration.md
While trying to setup the flags, I noticed this was not documented.
=> docs: add possible values for window_flags

status/kube.conf
As per
https://github.com/catppuccin/tmux/issues/301#issuecomment-2475898956 this issue has returned in v2.0
=> Escape TPM env var

status/pomodoro_plus.conf
Closes https://github.com/catppuccin/tmux/issues/453
=> fix: pomodoro plugin icon color

.github/workflows/whiskers-check.yml, tmux.tera
The template wasn't updated in #562 so adding our standard whiskers check workflow to prevent this in the future and updating the template / removing dead code.
=> refactor: add whiskers check & update template
